### ISSUE TITLE
The function delineate_watershed should not require epsg_code as an input

### ISSUE THREAD

**Issue by dtarb** [CI-WATER/hydrogate_python_client#1]
The projection information used for the output of this function should be taken from the digital elevation model input.

**Comment by tsga** [comment]
As I understand (Pabitra will correct me otherwise) in hydrogate python client the function is 'overloaded', i.e. you can either pass an outlet shape file and no need for epsg code, or you can pass outlet location coordinates with epsg code (This way we have both delineation options: from outlet point or from outlet shapefile).

**Comment by pkdash** [comment]
@tsga is correct in describing how this function is implemented.

**Comment by dtarb** [comment]
OK.  I deleted this from the argument list and the function still seems to work.
